import subprocess



for s in [ 
           ## closure tests
           "python unfoldTopPt.py --closureTest --addNoBtag",
           "python unfoldTopPt.py --closureTest --addNoBtag --lepType=ele",
           "python unfoldTopPt.py --closureTest --addNoBtag --twoStep",
           "python unfoldTopPt.py --closureTest --addNoBtag --twoStep --lepType=ele",
           
           ## unfolding, combining the 1 top-tag, 1 b-tag and 1 top-tag, 0 b-tag regions
           "python unfoldTopPt.py --addNoBtag --lepType=ele",
           "python unfoldTopPt.py --addNoBtag --lepType=ele --systVariation=toptagFITup",
           "python unfoldTopPt.py --addNoBtag --lepType=ele --systVariation=toptagFITdn",
           "python unfoldTopPt.py --addNoBtag --lepType=ele --systVariation=jerup",
           "python unfoldTopPt.py --addNoBtag --lepType=ele --systVariation=jerdn",
           "python unfoldTopPt.py --addNoBtag --lepType=ele --systVariation=jecup",
           "python unfoldTopPt.py --addNoBtag --lepType=ele --systVariation=jecdn",
           "python unfoldTopPt.py --addNoBtag --lepType=ele --systVariation=btagup",
           "python unfoldTopPt.py --addNoBtag --lepType=ele --systVariation=btagdn",
           "python unfoldTopPt.py --addNoBtag --lepType=ele --ttbarPDF=CT10_pdfup",
           "python unfoldTopPt.py --addNoBtag --lepType=ele --ttbarPDF=CT10_pdfdown",
           "python unfoldTopPt.py --addNoBtag --lepType=ele --ttbarPDF=scaleup",
           "python unfoldTopPt.py --addNoBtag --lepType=ele --ttbarPDF=scaledown",

           "python unfoldTopPt.py --addNoBtag",           
           "python unfoldTopPt.py --addNoBtag --systVariation=toptagFITup",
           "python unfoldTopPt.py --addNoBtag --systVariation=toptagFITdn",
           "python unfoldTopPt.py --addNoBtag --systVariation=jerup",
           "python unfoldTopPt.py --addNoBtag --systVariation=jerdn",
           "python unfoldTopPt.py --addNoBtag --systVariation=jecup",
           "python unfoldTopPt.py --addNoBtag --systVariation=jecdn",
           "python unfoldTopPt.py --addNoBtag --systVariation=btagup",
           "python unfoldTopPt.py --addNoBtag --systVariation=btagdn",
           "python unfoldTopPt.py --addNoBtag --ttbarPDF=CT10_pdfup",
           "python unfoldTopPt.py --addNoBtag --ttbarPDF=CT10_pdfdown",
           "python unfoldTopPt.py --addNoBtag --ttbarPDF=scaleup",
           "python unfoldTopPt.py --addNoBtag --ttbarPDF=scaledown",

           "python unfoldTopPt.py --addNoBtag --twoStep --lepType=ele",           
           "python unfoldTopPt.py --addNoBtag --twoStep --lepType=ele --systVariation=toptagFITup",
           "python unfoldTopPt.py --addNoBtag --twoStep --lepType=ele --systVariation=toptagFITdn",
           "python unfoldTopPt.py --addNoBtag --twoStep --lepType=ele --systVariation=jerup",
           "python unfoldTopPt.py --addNoBtag --twoStep --lepType=ele --systVariation=jerdn",
           "python unfoldTopPt.py --addNoBtag --twoStep --lepType=ele --systVariation=jecup",
           "python unfoldTopPt.py --addNoBtag --twoStep --lepType=ele --systVariation=jecdn",
           "python unfoldTopPt.py --addNoBtag --twoStep --lepType=ele --systVariation=btagup",
           "python unfoldTopPt.py --addNoBtag --twoStep --lepType=ele --systVariation=btagdn",
           "python unfoldTopPt.py --addNoBtag --twoStep --lepType=ele --ttbarPDF=CT10_pdfup",
           "python unfoldTopPt.py --addNoBtag --twoStep --lepType=ele --ttbarPDF=CT10_pdfdown",
           "python unfoldTopPt.py --addNoBtag --twoStep --lepType=ele --ttbarPDF=scaleup",
           "python unfoldTopPt.py --addNoBtag --twoStep --lepType=ele --ttbarPDF=scaledown",

           "python unfoldTopPt.py --addNoBtag --twoStep",           
           "python unfoldTopPt.py --addNoBtag --twoStep --systVariation=toptagFITup",
           "python unfoldTopPt.py --addNoBtag --twoStep --systVariation=toptagFITdn",
           "python unfoldTopPt.py --addNoBtag --twoStep --systVariation=jerup",
           "python unfoldTopPt.py --addNoBtag --twoStep --systVariation=jerdn",
           "python unfoldTopPt.py --addNoBtag --twoStep --systVariation=jecup",
           "python unfoldTopPt.py --addNoBtag --twoStep --systVariation=jecdn",
           "python unfoldTopPt.py --addNoBtag --twoStep --systVariation=btagup",
           "python unfoldTopPt.py --addNoBtag --twoStep --systVariation=btagdn",
           "python unfoldTopPt.py --addNoBtag --twoStep --ttbarPDF=CT10_pdfup",
           "python unfoldTopPt.py --addNoBtag --twoStep --ttbarPDF=CT10_pdfdown",
           "python unfoldTopPt.py --addNoBtag --twoStep --ttbarPDF=scaleup",
           "python unfoldTopPt.py --addNoBtag --twoStep --ttbarPDF=scaledown",


           ## unfolding using 1 top-tag, 1 b-tag region only
           "python unfoldTopPt.py --lepType=ele",
           "python unfoldTopPt.py --lepType=ele --systVariation=toptagFITup",
           "python unfoldTopPt.py --lepType=ele --systVariation=toptagFITdn",
           "python unfoldTopPt.py --lepType=ele --systVariation=jerup",
           "python unfoldTopPt.py --lepType=ele --systVariation=jerdn",
           "python unfoldTopPt.py --lepType=ele --systVariation=jecup",
           "python unfoldTopPt.py --lepType=ele --systVariation=jecdn",
           "python unfoldTopPt.py --lepType=ele --systVariation=btagup",
           "python unfoldTopPt.py --lepType=ele --systVariation=btagdn",
           "python unfoldTopPt.py --lepType=ele --ttbarPDF=CT10_pdfup",
           "python unfoldTopPt.py --lepType=ele --ttbarPDF=CT10_pdfdown",
           "python unfoldTopPt.py --lepType=ele --ttbarPDF=scaleup",
           "python unfoldTopPt.py --lepType=ele --ttbarPDF=scaledown",

           "python unfoldTopPt.py",           
           "python unfoldTopPt.py --systVariation=toptagFITup",
           "python unfoldTopPt.py --systVariation=toptagFITdn",
           "python unfoldTopPt.py --systVariation=jerup",
           "python unfoldTopPt.py --systVariation=jerdn",
           "python unfoldTopPt.py --systVariation=jecup",
           "python unfoldTopPt.py --systVariation=jecdn",
           "python unfoldTopPt.py --systVariation=btagup",
           "python unfoldTopPt.py --systVariation=btagdn",
           "python unfoldTopPt.py --ttbarPDF=CT10_pdfup",
           "python unfoldTopPt.py --ttbarPDF=CT10_pdfdown",
           "python unfoldTopPt.py --ttbarPDF=scaleup",
           "python unfoldTopPt.py --ttbarPDF=scaledown",

           "python unfoldTopPt.py --twoStep --lepType=ele",           
           "python unfoldTopPt.py --twoStep --lepType=ele --systVariation=toptagFITup",
           "python unfoldTopPt.py --twoStep --lepType=ele --systVariation=toptagFITdn",
           "python unfoldTopPt.py --twoStep --lepType=ele --systVariation=jerup",
           "python unfoldTopPt.py --twoStep --lepType=ele --systVariation=jerdn",
           "python unfoldTopPt.py --twoStep --lepType=ele --systVariation=jecup",
           "python unfoldTopPt.py --twoStep --lepType=ele --systVariation=jecdn",
           "python unfoldTopPt.py --twoStep --lepType=ele --systVariation=btagup",
           "python unfoldTopPt.py --twoStep --lepType=ele --systVariation=btagdn",
           "python unfoldTopPt.py --twoStep --lepType=ele --ttbarPDF=CT10_pdfup",
           "python unfoldTopPt.py --twoStep --lepType=ele --ttbarPDF=CT10_pdfdown",
           "python unfoldTopPt.py --twoStep --lepType=ele --ttbarPDF=scaleup",
           "python unfoldTopPt.py --twoStep --lepType=ele --ttbarPDF=scaledown",

           "python unfoldTopPt.py --twoStep",           
           "python unfoldTopPt.py --twoStep --systVariation=toptagFITup",
           "python unfoldTopPt.py --twoStep --systVariation=toptagFITdn",
           "python unfoldTopPt.py --twoStep --systVariation=jerup",
           "python unfoldTopPt.py --twoStep --systVariation=jerdn",
           "python unfoldTopPt.py --twoStep --systVariation=jecup",
           "python unfoldTopPt.py --twoStep --systVariation=jecdn",
           "python unfoldTopPt.py --twoStep --systVariation=btagup",
           "python unfoldTopPt.py --twoStep --systVariation=btagdn",
           "python unfoldTopPt.py --twoStep --ttbarPDF=CT10_pdfup",
           "python unfoldTopPt.py --twoStep --ttbarPDF=CT10_pdfdown",
           "python unfoldTopPt.py --twoStep --ttbarPDF=scaleup",
           "python unfoldTopPt.py --twoStep --ttbarPDF=scaledown",
           
           ] : 
    print s
    subprocess.call( [s, ""], shell=True )
    
    
