import FWCore.ParameterSet.Config as cms

cutbasedIDSelector = cms.PSet(
   # useData_  = cms.bool(True),
    version  = cms.string('TIGHT'),    
    deta_EB  =  cms.double(4.0e-03),
    dphi_EB  =  cms.double(3.0e-02),
    sihih_EB =  cms.double(1.0e-02),
    hoe_EB   =  cms.double(1.2e-01), 
    d0_EB    =  cms.double(2.0e-02),
    dZ_EB    =  cms.double(1.0e-01), 
    ooemoop_EB = cms.double(5.0e-02),
    reliso_EB  = cms.double(1.0e-01),
    deta_EE    = cms.double(5.0e-03),
    dphi_EE    = cms.double(2.0e-02),
    sihih_EE   = cms.double(3.0e-02),
    hoe_EE     = cms.double(1.0e-02),
    d0_EE      = cms.double(2.0e-02),
    dZ_EE      = cms.double(1.0e-01),
    ooemoop_EE = cms.double(5.0e-02),
    reliso_EE  = cms.double(1.0e-01),
    mHits      = cms.int32(0),
    vtxFitConv = cms.bool(True),
    pvSrc      = cms.InputTag("goodOfflinePrimaryVertices"),
    rhoSrc     = cms.InputTag('kt6PFJets', 'rho'),
    cutsToIgnore = cms.vstring(""), 
    )
