import FWCore.ParameterSet.Config as cms

# from 

def RecoInput() : 
 return cms.Source("PoolSource",
                   debugVerbosity = cms.untracked.uint32(200),
                   debugFlag = cms.untracked.bool(True),
                   
                   fileNames = cms.untracked.vstring(
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_100.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_10.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_11.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_12.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_13.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_14.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_15.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_16.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_17.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_18.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_19.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_1.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_20.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_21.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_22.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_23.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_24.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_25.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_26.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_27.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_28.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_29.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_2.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_30.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_31.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_32.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_33.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_34.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_35.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_36.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_37.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_38.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_39.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_3.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_40.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_41.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_42.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_43.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_44.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_45.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_46.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_47.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_48.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_49.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_4.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_50.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_51.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_52.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_53.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_54.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_55.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_56.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_57.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_58.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_59.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_5.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_60.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_61.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_62.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_63.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_64.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_65.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_66.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_67.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_68.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_69.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_6.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_70.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_71.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_72.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_73.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_74.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_75.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_76.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_77.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_78.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_79.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_7.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_80.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_81.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_82.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_83.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_84.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_85.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_86.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_87.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_88.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_89.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_8.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_90.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_91.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_92.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_93.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_94.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_95.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_96.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_97.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_98.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_99.root',
'dcache:/pnfs/cms/WAX/resilient/baites/wjets/production/wc_10TeV_9.root'

     
     )
                   )
