/********************************************************************
* /uscms_data/d3/skinnari/TopXS_slc5/CMSSW_5_3_22_patch1/src/Analysis/IHeartNY/test/RooUnfold-1.1.1/tmp/linuxx8664gcc/RooUnfoldDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /uscms_data/d3/skinnari/TopXS_slc5/CMSSW_5_3_22_patch1/src/Analysis/IHeartNY/test/RooUnfold-1.1.1/tmp/linuxx8664gcc/RooUnfoldDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableRooUnfoldDict();
extern void G__cpp_setup_inheritanceRooUnfoldDict();
extern void G__cpp_setup_typetableRooUnfoldDict();
extern void G__cpp_setup_memvarRooUnfoldDict();
extern void G__cpp_setup_globalRooUnfoldDict();
extern void G__cpp_setup_memfuncRooUnfoldDict();
extern void G__cpp_setup_funcRooUnfoldDict();
extern void G__set_cpp_environmentRooUnfoldDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/uscms_data/d3/skinnari/TopXS_slc5/CMSSW_5_3_22_patch1/src/Analysis/IHeartNY/test/RooUnfold-1.1.1/src/RooUnfold.h"
#include "/uscms_data/d3/skinnari/TopXS_slc5/CMSSW_5_3_22_patch1/src/Analysis/IHeartNY/test/RooUnfold-1.1.1/src/RooUnfoldBayes.h"
#include "/uscms_data/d3/skinnari/TopXS_slc5/CMSSW_5_3_22_patch1/src/Analysis/IHeartNY/test/RooUnfold-1.1.1/src/RooUnfoldBinByBin.h"
#include "/uscms_data/d3/skinnari/TopXS_slc5/CMSSW_5_3_22_patch1/src/Analysis/IHeartNY/test/RooUnfold-1.1.1/src/RooUnfoldErrors.h"
#include "/uscms_data/d3/skinnari/TopXS_slc5/CMSSW_5_3_22_patch1/src/Analysis/IHeartNY/test/RooUnfold-1.1.1/src/RooUnfoldInvert.h"
#include "/uscms_data/d3/skinnari/TopXS_slc5/CMSSW_5_3_22_patch1/src/Analysis/IHeartNY/test/RooUnfold-1.1.1/src/RooUnfoldParms.h"
#include "/uscms_data/d3/skinnari/TopXS_slc5/CMSSW_5_3_22_patch1/src/Analysis/IHeartNY/test/RooUnfold-1.1.1/src/RooUnfoldResponse.h"
#include "/uscms_data/d3/skinnari/TopXS_slc5/CMSSW_5_3_22_patch1/src/Analysis/IHeartNY/test/RooUnfold-1.1.1/src/RooUnfoldSvd.h"
#include "/uscms_data/d3/skinnari/TopXS_slc5/CMSSW_5_3_22_patch1/src/Analysis/IHeartNY/test/RooUnfold-1.1.1/src/RooUnfoldTUnfold.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__RooUnfoldDictLN_TClass;
extern G__linked_taginfo G__RooUnfoldDictLN_TBuffer;
extern G__linked_taginfo G__RooUnfoldDictLN_TMemberInspector;
extern G__linked_taginfo G__RooUnfoldDictLN_TObject;
extern G__linked_taginfo G__RooUnfoldDictLN_TNamed;
extern G__linked_taginfo G__RooUnfoldDictLN_TString;
extern G__linked_taginfo G__RooUnfoldDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__RooUnfoldDictLN_vectorlEdoublecOallocatorlEdoublegRsPgRcLcLiterator;
extern G__linked_taginfo G__RooUnfoldDictLN_reverse_iteratorlEvectorlEdoublecOallocatorlEdoublegRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__RooUnfoldDictLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__RooUnfoldDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__RooUnfoldDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__RooUnfoldDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__RooUnfoldDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__RooUnfoldDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__RooUnfoldDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__RooUnfoldDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__RooUnfoldDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__RooUnfoldDictLN_TElementActionTlEdoublegR;
extern G__linked_taginfo G__RooUnfoldDictLN_TElementPosActionTlEdoublegR;
extern G__linked_taginfo G__RooUnfoldDictLN_TMatrixTRow_constlEdoublegR;
extern G__linked_taginfo G__RooUnfoldDictLN_TMatrixTlEdoublegR;
extern G__linked_taginfo G__RooUnfoldDictLN_TMatrixTSymlEdoublegR;
extern G__linked_taginfo G__RooUnfoldDictLN_TMatrixTRowlEdoublegR;
extern G__linked_taginfo G__RooUnfoldDictLN_TMatrixTSparselEdoublegR;
extern G__linked_taginfo G__RooUnfoldDictLN_TMatrixTSparseRow_constlEdoublegR;
extern G__linked_taginfo G__RooUnfoldDictLN_TMatrixTSparseRowlEdoublegR;
extern G__linked_taginfo G__RooUnfoldDictLN_TMatrixTDiag_constlEdoublegR;
extern G__linked_taginfo G__RooUnfoldDictLN_TMatrixTColumn_constlEdoublegR;
extern G__linked_taginfo G__RooUnfoldDictLN_TMatrixTSparseDiag_constlEdoublegR;
extern G__linked_taginfo G__RooUnfoldDictLN_TMatrixTFlat_constlEdoublegR;
extern G__linked_taginfo G__RooUnfoldDictLN_TMatrixTSub_constlEdoublegR;
extern G__linked_taginfo G__RooUnfoldDictLN_TMatrixTColumnlEdoublegR;
extern G__linked_taginfo G__RooUnfoldDictLN_TMatrixTDiaglEdoublegR;
extern G__linked_taginfo G__RooUnfoldDictLN_TMatrixTFlatlEdoublegR;
extern G__linked_taginfo G__RooUnfoldDictLN_TMatrixTSublEdoublegR;
extern G__linked_taginfo G__RooUnfoldDictLN_TMatrixTSparseDiaglEdoublegR;
extern G__linked_taginfo G__RooUnfoldDictLN_TAxis;
extern G__linked_taginfo G__RooUnfoldDictLN_TH1D;
extern G__linked_taginfo G__RooUnfoldDictLN_TH1;
extern G__linked_taginfo G__RooUnfoldDictLN_TH2;
extern G__linked_taginfo G__RooUnfoldDictLN_TH2D;
extern G__linked_taginfo G__RooUnfoldDictLN_RooUnfoldResponse;
extern G__linked_taginfo G__RooUnfoldDictLN_RooUnfold;
extern G__linked_taginfo G__RooUnfoldDictLN_RooUnfoldcLcLAlgorithm;
extern G__linked_taginfo G__RooUnfoldDictLN_RooUnfoldcLcLErrorTreatment;
extern G__linked_taginfo G__RooUnfoldDictLN_RooUnfoldBayes;
extern G__linked_taginfo G__RooUnfoldDictLN_RooUnfoldBinByBin;
extern G__linked_taginfo G__RooUnfoldDictLN_TNtuple;
extern G__linked_taginfo G__RooUnfoldDictLN_RooUnfoldErrors;
extern G__linked_taginfo G__RooUnfoldDictLN_TDecompSVD;
extern G__linked_taginfo G__RooUnfoldDictLN_RooUnfoldInvert;
extern G__linked_taginfo G__RooUnfoldDictLN_TProfile;
extern G__linked_taginfo G__RooUnfoldDictLN_RooUnfoldParms;
extern G__linked_taginfo G__RooUnfoldDictLN_TSVDUnfold;
extern G__linked_taginfo G__RooUnfoldDictLN_RooUnfoldSvd;
extern G__linked_taginfo G__RooUnfoldDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__RooUnfoldDictLN_TUnfold;
extern G__linked_taginfo G__RooUnfoldDictLN_TUnfoldcLcLERegMode;
extern G__linked_taginfo G__RooUnfoldDictLN_RooUnfoldTUnfold;
extern G__linked_taginfo G__RooUnfoldDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__RooUnfoldDictLN_vectorlEintcOallocatorlEintgRsPgRcLcLiterator;
extern G__linked_taginfo G__RooUnfoldDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
typedef vector<double,allocator<double> > G__vectorlEdoublecOallocatorlEdoublegRsPgR;
typedef vector<int,allocator<int> > G__vectorlEintcOallocatorlEintgRsPgR;
